version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - gosec
    - misspell
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - wastedassign
    - whitespace
  settings:
    godot:
      scope: all
      capital: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
