linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - goimports
    - gosec
    - misspell
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - wastedassign
    - whitespace
linters-settings:
  godot:
    scope: all
    capital: true
issues:
  fix: true
